In [1]:
import sys
!{sys.executable} -m pip install numpy

# when ever you install anything just use this command to install or else use pip install package name


flake8 3.6.0 requires pycodestyle<2.5.0,>=2.4.0, which is not installed.
flake8 3.6.0 requires pyflakes<2.1.0,>=2.0.0, which is not installed.
autopep8 1.4.4 requires pycodestyle>=2.4.0, which is not installed.
mysql-connector-python 8.0.18 requires protobuf>=3.0.0, which is not installed.
You are using pip version 10.0.1, however version 20.2b1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [3]:
import numpy as np
b=[1,2,3,4,5,6,7]
c=np.array(b)
print(type(c))


<class 'numpy.ndarray'>


In [4]:
import sys
!{sys.executable} -m pip install sklearn


flake8 3.6.0 requires pycodestyle<2.5.0,>=2.4.0, which is not installed.
flake8 3.6.0 requires pyflakes<2.1.0,>=2.0.0, which is not installed.
autopep8 1.4.4 requires pycodestyle>=2.4.0, which is not installed.
mysql-connector-python 8.0.18 requires protobuf>=3.0.0, which is not installed.
You are using pip version 10.0.1, however version 20.2b1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [5]:
import sys
!{sys.executable} -m pip install selenium

flake8 3.6.0 requires pycodestyle<2.5.0,>=2.4.0, which is not installed.
flake8 3.6.0 requires pyflakes<2.1.0,>=2.0.0, which is not installed.
autopep8 1.4.4 requires pycodestyle>=2.4.0, which is not installed.
mysql-connector-python 8.0.18 requires protobuf>=3.0.0, which is not installed.
You are using pip version 10.0.1, however version 20.2b1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [2]:
import sys
!{sys.executable} -m pip install matplotlib

flake8 3.6.0 requires pycodestyle<2.5.0,>=2.4.0, which is not installed.
flake8 3.6.0 requires pyflakes<2.1.0,>=2.0.0, which is not installed.
autopep8 1.4.4 requires pycodestyle>=2.4.0, which is not installed.
mysql-connector-python 8.0.18 requires protobuf>=3.0.0, which is not installed.
You are using pip version 10.0.1, however version 20.2b1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [11]:
a=[1,2,3,4.5,6]
b=np.array(a*3)
b

array([1. , 2. , 3. , 4.5, 6. , 1. , 2. , 3. , 4.5, 6. , 1. , 2. , 3. ,
       4.5, 6. ])

In [12]:
# by default the dtype or datatype is float
b=np.ones(3)
b

array([1., 1., 1.])

In [13]:
b=np.zeros(3)
b

array([0., 0., 0.])

In [14]:
b=np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
b=np.zeros((3,4),dtype = int)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
b=np.ones((3,6),dtype=int)
b

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [17]:
# by default the dtype is int and can be changed to any data type
b=np.full((3,4),21)
b

array([[21, 21, 21, 21],
       [21, 21, 21, 21],
       [21, 21, 21, 21]])

In [23]:
# it will give a array of required size that is initialized with random entries
b=np.empty(4,dtype=int)
b

array([1364368416,        616,          0,          0])

In [26]:
b=np.empty((4,4),dtype=int)
b

array([[   0,    0,    0,    0],
       [   0,    0,    0,    0],
       [   0,    0, 1380,    0],
       [   0,   54,    0,    0]])

In [27]:
# it will create an entry in the range 0-1.
b=np.random.rand(3)
b

array([0.74524888, 0.21509966, 0.37845125])

In [28]:
b=np.random.rand(3)*100
b

array([97.09077748, 15.89956047, 80.05081618])

In [30]:
b=np.random.rand(2,3)*100
b

array([[15.32776854, 24.17515532, 15.70837553],
       [26.2396444 ,  1.98437922, 10.01083725]])

In [33]:
# it will give a random int value in the range specified eg. (2,10)
b=np.random.randint(2,10)
b

6

In [35]:
#entry of m*m identity matrix.
b=np.identity(4)
b



array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
#entry of m*n identity matrix.
b=np.eye(4,5)
b


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [39]:
#(start,end ,skip)
b=np.arange(2,20,2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
#(start,end) 
b=np.linspace(2,10)
b

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [45]:
#(start,end,no.of elements) will not include the last end point.
b=np.linspace(2,10,7,dtype = int,endpoint=False)
b

array([2, 3, 4, 5, 6, 7, 8])

# now we will start working on 2d data.


In [1]:
li2=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

In [5]:
arr_2d=np.array(li2)
print(arr_2d.data)
print(arr_2d.dtype)
print(arr_2d.shape)
print(arr_2d)

int32
(4, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [6]:
print(arr_2d[0:3,2]) # this is unsually from the normal 2d array behavior that will print[9,10,11,12]

[ 3  7 11]


In [7]:
print(arr_2d[2,0:3])

[ 9 10 11]


# now we will look at the mathematical operations on numpy

In [12]:
a=np.random.randint(1,20,5)
b=np.random.randint(1,20,5)
print(a)
print(b)

[17 15 14 17 10]
[ 6 18 16 17  9]


In [13]:
a=a+1
print(a)

[18 16 15 18 11]


In [14]:
c=a-1
print(c)

[17 15 14 17 10]


In [15]:
c=a+b
print(c)


[24 34 31 35 20]


In [16]:
c=a/b
print(c)

[3.         0.88888889 0.9375     1.05882353 1.22222222]


In [17]:
c=a*b
print(c)

[108 288 240 306  99]


In [18]:
c=a//b
print(c)

[3 0 0 1 1]


In [19]:
c=a**b
print(c)

[   34012224           0  1039759105  1695678464 -1937019605]


In [20]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[18 16 15 18 11]
78
15.6
11
4
18
0


In [21]:
print(np.logical_or(a,b)) # true if not equal to 0 .
print(np.logical_and(a,b))
print(np.logical_not(a))# false for value not equal to 0.

[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]


# we study about the boolean indexing

In [22]:
print(b>10)

[False  True  True  True False]


In [23]:
bool_arr=b>10
print(bool_arr)
new_arr=b[bool_arr]
print(new_arr)

[False  True  True  True False]
[18 16 17]


In [25]:
# it can be further written into 
new_arr1=b[b>10]
print(new_arr1)

[        28         28         28 1695678464]


In [26]:
new_arr2=b[(b>10)&(b<20)]
print(new_arr2)

[]


In [24]:
b=c # change the values in single time
c[:3]=28
c

array([         28,          28,          28,  1695678464, -1937019605],
      dtype=int32)

In [33]:

indx=np.where(c==28)
indx

(array([0, 1, 2], dtype=int64),)

In [34]:
d=np.random.randint(1,10,(4,4))
d

array([[6, 6, 6, 4],
       [4, 3, 6, 9],
       [5, 9, 7, 3],
       [2, 4, 2, 8]])

In [35]:
d[d>8]

array([9, 9])

In [36]:
d[d>8]=20


In [37]:
d

array([[ 6,  6,  6,  4],
       [ 4,  3,  6, 20],
       [ 5, 20,  7,  3],
       [ 2,  4,  2,  8]])

In [42]:
bool_arr1=d[:3]==20
print(bool_arr1)

[[False False False False]
 [False False False  True]
 [False  True False False]]


In [47]:
d=np.transpose(d)
print(d)

[[ 6  4  5  2]
 [ 6  3 20  4]
 [ 6  6  7  2]
 [ 4 20  3  8]]


In [55]:
d=np.resize(5,(4,4))
print(d)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [56]:
d=np.resize(5,4)
print(d)

[5 5 5 5]


# 